### PR TITLE
Milestone 1 : Hello Microverse Project

### PR DESCRIPTION
**Pull request by AkshithaReddy1899**
# Hello Microverse

This PR is raised to master the best practices while writing code

# Description of the task to be completed

- Used Github workflow
- Configured the project to use linters
- Added a .HTML file that includes a header
- Styled the header component
- Added a gitignore file
- Added a test.md file which was ignored by git
- Fixed linter errors
- Added descriptive README
- Added a descriptive PR
- Capitalized commit messages

### CODE REVIEW

**Comment by carlos-ssh** [comment]
# 🚫⚠️🛑 INVALID SUBMISSION 🚫⚠️🛑
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that ``INVALID PROJECT LINK.`` kindly send the right link for your code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Rustamxon7 — CHANGES_REQUESTED** [review]
## Hi @AkshithaReddy1899 👋🏾 , 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
#### Highlights
- not forming any linter errors ✔️ 

## Required Changes ♻️

- [x] Your Pull Request should have a description of what you have built. I would kindly suggest filling this place. 😊

 
Screen Shot 2021-11-23 at 7 02 51 PM



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

**Review by enaburekhan — CHANGES_REQUESTED** [review]
Hi AkshithaReddy, 

Great work on making the changes 👏 
You've done well implementing the optional requested changes for the readme, but there are still some which aren't addressed yet.


## Suggested changes

- [x] As already suggested by the last reviewer, I will encourage you to add a descriptive pull request (PR) to your project. Check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) to get hints on how to write a descriptive PR.


Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by AkshithaReddy1899** [comment]
Hello, @enaburekhan I have made some changes, not sure if that's enough but also the link you have provided for reference takes me to microversepathwright.com and I can't find anything there so, I was wondering if you could be kind enough to send me another link about descriptive PR.

Screenshot (4)

**Comment by enaburekhan** [comment]
Hi  AkshithaReddy,
I just clicked on the [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) again and it took me there: I mean this page; 
image
After clicking, just be patient for while, and then scroll down to the page.

Let me know if you are still having issues with link.

**Review by carlos-ssh — APPROVED** [review]
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi @AkshithaReddy1899 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Approved


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
